# -*- coding: utf-8 -*-
"""bickley_parameters.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgG0Wk5xjZkH7A7-xb1qdiTlf4jfE58D
"""

"""
Defines the canonical Bickley Jet parameters.
"""

import numpy as np

U = (62.66 * 60 * 60 * 24) / 1e6
L = 1.77
r0 = 6.371000

k1 = 2 / r0
k2 = 4 / r0
k3 = 6 / r0

e1 = 0.075
e2 = 0.4
e3 = 0.3

c3 = 0.461 * U
c2 = 0.205 * U
c1 = c3 + ((np.sqrt(5) - 1) / 2) * (k2 / k1) * (c2 - c3)

params = [U, L, r0, k1, k2, k3, e1, e2, e3, c3, c2, c1]