# -*- coding: utf-8 -*-
"""domain_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEKBHFL4RHYTowwhL1DWLOvi0XM3KXtl
"""

"""
Domain and grid utilities for Bickley Jet simulations.
"""

import numpy as np
from src.bickley_parameters import r0

def get_domain(Nx=200, Ny=80, yBound=(-3,3)):
    xBound = (0, np.pi * r0)
    x = np.linspace(xBound[0], xBound[1], Nx)
    y = np.linspace(yBound[0], yBound[1], Ny)
    X, Y = np.meshgrid(x, y)
    return x, y, X, Y, xBound, yBound

