# -*- coding: utf-8 -*-
"""plot_t_slice_particles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhUCnaBj6iuWPwCo5aqMAlQdJol39vQy
"""

"""
plot_tslice_particles.py
------------------------

Loads precomputed trajectories from trajectories.npy and plots the particle
positions at a chosen time slice.
"""

import numpy as np
import matplotlib.pyplot as plt

from src.domain_setup import get_domain

# ----------------------------------------------------
# Load trajectory data
# ----------------------------------------------------
Traj = np.load("trajectories.npy")  # shape = (numTraj, numTimes, 2)

numTraj, numTimes, _ = Traj.shape
_, _, _, _, xBound, yBound = get_domain()

# ----------------------------------------------------
# Choose time index
# ----------------------------------------------------
t_index = 20  # change as desired

x_at_t = Traj[:, t_index, 0]
y_at_t = Traj[:, t_index, 1]

# ----------------------------------------------------
# Plot positions
# ----------------------------------------------------
plt.figure(figsize=(12, 4))
plt.scatter(x_at_t, y_at_t, s=12, color="blue")
plt.xlim(xBound)
plt.ylim(yBound)
plt.xlabel("x (Mm)")
plt.ylabel("y (Mm)")
plt.title(f"Bickley Jet Particle Positions at Time Index t={t_index}")

plt.tight_layout()
plt.show()