# -*- coding: utf-8 -*-
"""plot_bickley_streamlines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0NthmiL5SNaTtM26pqkU_D3Sp6306dU
"""

"""
plot_bickley_streamlines.py
---------------------------

Generates a colorful streamline plot of the Bickley Jet at t=0, and overlays
initial particle locations. Demonstrates Eulerian velocity field usage.
"""

import numpy as np
import matplotlib.pyplot as plt

from src.bickley_parameters import params
from src.bickley_velocity import BickleyJet_velocity_field
from src.domain_setup import get_domain

# ----------------------------------------------------
# Get domain and grid
# ----------------------------------------------------
x, y, X, Y, xBound, yBound = get_domain(Nx=300, Ny=120)

# ----------------------------------------------------
# Compute velocity field
# ----------------------------------------------------
t_eval = 0
u, v = BickleyJet_velocity_field(X, Y, t_eval, params)
speed = np.sqrt(u**2 + v**2)

# ----------------------------------------------------
# Generate initial particle positions
# ----------------------------------------------------
numTraj = 100
ICs_x = np.random.uniform(xBound[0], xBound[1], numTraj)
ICs_y = np.random.uniform(yBound[0], yBound[1], numTraj)

# ----------------------------------------------------
# Plot streamlines with speed-based colormap
# ----------------------------------------------------
fig, ax = plt.subplots(figsize=(14, 4))

strm = ax.streamplot(
    x, y, u, v,
    density=2.0,
    color=speed,
    cmap='turbo',
    linewidth=1.0
)

cbar = plt.colorbar(strm.lines)
cbar.set_label("Speed (Mm/day)")

# Overlay initial particles
ax.scatter(ICs_x, ICs_y, s=18, color='white', edgecolors='black', linewidth=0.5)

ax.set_xlim(xBound)
ax.set_ylim(yBound)
ax.set_xlabel("x (Mm)")
ax.set_ylabel("y (Mm)")
ax.set_title("Bickley Jet Streamlines + Initial Particles")

plt.tight_layout()
plt.show()